### ISSUE TITLE
[Format] Add YAML output

### ISSUE THREAD

**Issue by hahwul** [hahwul/noir#121]

**Comment by hahwul** [comment]
## Test
```yaml
# noir -b ./sinatra/ -f yaml
# ...
# [I] Finally identified 2 endpoints.
# [*] Generating Report.
---
- url: /
  method: GET
  params:
  - name: query
    value: ""
    param_type: query
  headers: []
  protocol: http
- url: /update
  method: POST
  params: []
  headers: []
  protocol: http
```
